version: '3'

services:
  warehousemanagement-backend:
    build:
      context: ./WarehouseManagement-Backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  warehousemanagement-frontend:
    build:
      context: ./WarehouseManagement-Frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80

